version: '3.8'

services:

  postgres_db:
    image: postgres:17.6
    networks:
      - social-network
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d social-network-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  social-network-backend:
    build: .
    ports:
      - "443:8443"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - ./app-data:/data
      - /etc/ssl/mydomain:/etc/ssl/mydomain:ro
    networks:
      - social-network

networks:
  social-network:
    driver: bridge
